server:
    address: p.pjservice.cn
    tls: false
    token: sk_global_secret
    tunnel_path: /_tunnel/
proxy:
    s120:
        target: 192.168.0.36:8602
        tls: true
heartbeat:
    interval: 30
webui:
    enabled: true
    addr: :18080
